// <auto-generated />
using System;
using MOTILab3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOTILab3.Migrations
{
    [DbContext(typeof(MOTILab3Context))]
    [Migration("20211219153216_f")]
    partial class f
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MOTILab3.Models.ArmourResistanceResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArmourId")
                        .HasColumnType("int");

                    b.Property<int?>("EnemyWeaponWeaponId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayersArmourArmourId")
                        .HasColumnType("int");

                    b.Property<int>("ResistedDamage")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("EnemyWeaponWeaponId");

                    b.HasIndex("PlayersArmourArmourId");

                    b.ToTable("ArmourResistanceResult");
                });

            modelBuilder.Entity("MOTILab3.Models.EnemyWeapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("WeaponMagicalDamage")
                        .HasColumnType("int");

                    b.Property<string>("WeaponName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponPhysicalDamage")
                        .HasColumnType("int");

                    b.HasKey("WeaponId");

                    b.ToTable("EnemyWeapon");
                });

            modelBuilder.Entity("MOTILab3.Models.PlayersArmour", b =>
                {
                    b.Property<int>("ArmourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArmourMagicalResistance")
                        .HasColumnType("int");

                    b.Property<string>("ArmourName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArmourPhysicalResistance")
                        .HasColumnType("int");

                    b.HasKey("ArmourId");

                    b.ToTable("PlayersArmour");
                });

            modelBuilder.Entity("MOTILab3.Models.ArmourResistanceResult", b =>
                {
                    b.HasOne("MOTILab3.Models.EnemyWeapon", "EnemyWeapon")
                        .WithMany("ArmourResistanceResult")
                        .HasForeignKey("EnemyWeaponWeaponId");

                    b.HasOne("MOTILab3.Models.PlayersArmour", "PlayersArmour")
                        .WithMany("ArmourResistanceResult")
                        .HasForeignKey("PlayersArmourArmourId");

                    b.Navigation("EnemyWeapon");

                    b.Navigation("PlayersArmour");
                });

            modelBuilder.Entity("MOTILab3.Models.EnemyWeapon", b =>
                {
                    b.Navigation("ArmourResistanceResult");
                });

            modelBuilder.Entity("MOTILab3.Models.PlayersArmour", b =>
                {
                    b.Navigation("ArmourResistanceResult");
                });
#pragma warning restore 612, 618
        }
    }
}
